version: "3.9"
services:
  rtsp_server:
    image: bluenviron/mediamtx:1.5.1-ffmpeg
    container_name: rtsp_server
    ports:
      - 8554:8554
      - 1935:1935
      - 8888:8888
      - 8889:8889
      - 8890:8890/udp
      - 8189:8189/udp
    volumes:
      - ./${STOCK_VIDEO_RELATIVE_PATH}:/stock_video.mp4
      - ./rtsp-server/mediamtx.yml:/mediamtx.yml

  flask_server:
    build:
      context: flask-app/
      dockerfile: Dockerfile
      args:
        - yolo_model=yolov5s.onnx
    container_name: flask_server
    ports:
      - 8080:8080
    volumes:
      - ./output:/output
    env_file:
      - ./flask-app/.env.container
    depends_on:
      - rtsp_server
